### ISSUE TITLE
Is the  yaml  front-matter readonly?

### ISSUE THREAD

**Issue by xbotao** [jxson/front-matter#49]
Is this a readonly parse? If I want to change the yaml and save, what should I do?

**Comment by jxson** [comment]
Yeah, readonly.

You should take a look at [js-yaml](https://github.com/nodeca/js-yaml), it has writing support.

I intentionally avoided writing via this module since the YAML spec is too loose for there to be a clean merge when updating files. At some point this module should be pluggable too and not all formats are two-way.

**Comment by xbotao** [comment]
Tanks！

发自我的 iPhone
